"""Initial migration.

Revision ID: c472aa92e298
Revises: 360fbff48bba
Create Date: 2024-06-18 20:19:27.447176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c472aa92e298'
down_revision = '360fbff48bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('presentation_time', sa.DateTime(), nullable=False))
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('details',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('presentation_time')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
