"""Initial migration.

Revision ID: cb4e0312103a
Revises: c472aa92e298
Create Date: 2024-06-19 17:13:50.219189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4e0312103a'
down_revision = 'c472aa92e298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medic_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('treatment', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medic_id'], ['medics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_histories')
    # ### end Alembic commands ###
